var features = {
    COMMUNITIES_FAVORITE_BUTTON                     : true
};

var config = {
    default_language    : 'en_US',
    supported_languages : ['en_US', 'fr_FR', 'de'],
    current_language    : '',
    plugins             : {WIKIS_SIDEBAR_LINKS_ENABLE_SCROLLBAR : { WIKIS_SIDEBAR_LINKS_NAV_HEIGHT : '100px'}},
    is_cloud            : (typeof gllConnectionsData == "object" || typeof icUser == "object"),
    homepage_url        : "/homepage"
};


var strings={en_US:{ERASE:"Erase",DELETE:"Delete",CANCEL:"Cancel",DOWNLOAD_CSV:"Download CSV",ADD_TO_FAVOURITES:"Add to Favourites",FAVOURITED:"A Favourite Community",BULK_DELETE_MEMBERS:"Bulk delete members",NO_MEMBERS_SELECTED:"You have not selected any members to be deleted",CONFIRM_MEMBER_DELETE_1:"Are you sure you want to delete",CONFIRM_MEMBER_DELETE_2_1:" member",CONFIRM_MEMBER_DELETE_2_2:" members",CONFIRM_MEMBER_DELETE_3:"? There is no way to undo this action.",SELECT_ALL:"Select all",FAVOURITE_COMMUNITIES:"Favourite Communities",
MY_FAVOURITE_COMMUNITIES:"My favourite Communities",NO_COMMUNITIES_ADDED:"You have not added any communities to your favourites.",NUMBER_OF_PEOPLE_TO_BE_DELETED:"Number of people to be deleted:"},fr_FR:{ERASE:"Effacer",DELETE:"Supprimer",CANCEL:"Annuler",DOWNLOAD_CSV:"T\u00e9l\u00e9charger le CSV",ADD_TO_FAVOURITES:"Ajouter \u00e0 mes favoris",FAVOURITED:"Une communaut\u00e9 pr\u00e9f\u00e9r\u00e9e",BULK_DELETE_MEMBERS:"Supprimer des membres",NO_MEMBERS_SELECTED:"Vous n'avez pas selectionn\u00e9 de membre \u00e0 supprimer",
CONFIRM_MEMBER_DELETE_1:"\u00cates-vous s\u00fbr de vouloir supprimer",CONFIRM_MEMBER_DELETE_2_1:" membre",CONFIRM_MEMBER_DELETE_2_2:" membres",CONFIRM_MEMBER_DELETE_3:"? Il n'est pas possible d'annuler cette action.",SELECT_ALL:"Tout s\u00e9lectionner",FAVOURITE_COMMUNITIES:"Communaut\u00e9s Favorites",MY_FAVOURITE_COMMUNITIES:"Mes communaut\u00e9s pr\u00e9f\u00e9r\u00e9es",NO_COMMUNITIES_ADDED:"Vous n'avez pas de communaut\u00e9s favorites",NUMBER_OF_PEOPLE_TO_BE_DELETED:"Le nombre de personnes \u00e0 supprimer"},
de:{ADD_TO_FAVOURITES:"Zu Favoriten hinzuf\u00fcgen"}};function set_language(){var a=atob(dojo.cookie("user_lang").substring(0,dojo.cookie("user_lang").indexOf("=")));-1<config.supported_languages.indexOf(a)?config.current_language=a:config.current_language=config.default_language}function get_translation(a){return strings[config.current_language][a]}set_language();

features.COMMUNITIES_FAVORITE_BUTTON&&document.addEventListener("DOMContentLoaded",function(){function k(){var a=document.createElement("div");a.innerHTML='<style type="text/css">.ccet_modal_background{position:fixed;top:0;bottom:0;left:0;right:0;background-color:rgba(0,0,0,0.7);z-index:1500;}.ccet_modal{position:fixed;width:450px;height:500px;z-index:999999;top:50%;left:50%;margin:-250px 0 0 -225px;background:white;box-shadow:0 4px 8px 0 rgba(0, 0, 0, 0.2),0 6px 20px 0 rgba(0, 0, 0, 0.19);}.ccet_modal .header{width:100%;height:45px;background-color:#325c80;color:#FFFFFF;text-align:center;line-height:45px;font-size:22px;border-bottom:1px solid #264661;}.add_favorite_button:hover{cursor:pointer;}.community_favorite{background-position-x:54px;background-position-y:-11px;}.community_not_favorite{background-position-x:78px;background-position-y:-11px;}.ccet_modal .lotusLoading{width:160px !important;height:160px !important;left:calc(50% - 80px) !important;margin-top:118px;}</style>';
document.getElementsByTagName("body")[0].appendChild(a)}function l(){for(var a=document.querySelectorAll(".itemsPerPageLink a, li.prevPageLink a, li.nextPageLink a"),c=0;c<a.length;c++)a[c].addEventListener("click",function(){var b=setInterval(function(){null!==document.getElementById("lconn_communities_catalog_widgets_ResultsDisplayWidget_0")&&(l(),document.getElementById("favourite_communities_modal_link").outerHTML="",m(),clearInterval(b))},1E3)},!1)}function m(){h.onreadystatechange=function(){if(4==
this.readyState&&200==this.status){var b=JSON.parse(this.responseText);0!=b.message?n(b.message):n(null)}else return"failure"};h.open("GET","/muse/data/get/favorite_communities_"+gllConnectionsData.userId,!0);h.send();var a=document.createElement("li"),c=document.createElement("a");c.setAttribute("href","javascript:void(0);");c.appendChild(document.createTextNode(get_translation("FAVOURITE_COMMUNITIES")));a.setAttribute("id","favourite_communities_modal_link");a.appendChild(c);c.addEventListener("click",
function(){var b=document.createElement("div"),a=document.createElement("div"),c=document.createElement("div");b.className="ccet_modal_background";b.setAttribute("id","ccet_favourite_communities_modal");a.className="ccet_modal";a.innerHTML='<div class="header">'+get_translation("MY_FAVOURITE_COMMUNITIES")+'</div><div style="height:406px;overflow-y:scroll;" id="favourite_community_list"><img class="lotusLoading" style="height: 70px; width: 100%; background-position: center center" src="https://apps.na.collabserv.com/connections/resources/web/com.ibm.lconn.core.styles.oneui3/images/blank.gif?etag=20180815.153207"/></div><div><a style="display: inline-block;padding: 8px 17px;margin: 5px;border: 2px solid #325c80;" class="cancel_button" id="ccet_modal_cancel_button" href="javascript:void(0);">OK</a></div></div>';
a.appendChild(c);b.appendChild(a);document.getElementsByTagName("body")[0].appendChild(b);document.getElementById("ccet_modal_cancel_button").addEventListener("click",function(){document.getElementById("ccet_favourite_communities_modal").outerHTML=""},!1);p(function(b){for(var a=[],c=[],d=0,f=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,g=0;g<b.message.length;g++)if(null==b.message[g].match(f))console.log("expired community:"+b.message[g]),c.push(b.message[g]),d++,
d==b.message.length&&q(b,a,c);else{var e=new XMLHttpRequest;e.onreadystatechange=function(){if(4==this.readyState&&200==this.status){d++;var f=this.responseText.match(/<title type="text">(.*?)<\/title>/i),g=this.responseText.match(/<snx:communityUuid>(.*?)<\/snx:communityUuid>/i);-1==this.responseText.indexOf('<category term="deleted"')?a.push({community_name:f[1],community_id:g[1]}):c.push(g[1]);d==b.message.length&&q(b,a,c)}else return"failure"};e.open("GET","/communities/service/atom/forms/community/instance?communityUuid="+
b.message[g],!0);e.send()}if(0==b.message.length||0==b.message)document.getElementById("favourite_community_list").innerHTML='<div style="text-align:center;margin-top:50px;font-size:15px;">'+get_translation("NO_COMMUNITIES_ADDED")+"</div>"})},!1);document.getElementById("toolbar_catalog_menu").appendChild(a)}function q(a,c,b){if(0<b.length){a=a.message.filter(function(a){return 0>b.indexOf(a)});var d=new XMLHttpRequest;d.onreadystatechange=function(){4==this.readyState&&200==this.status&&console.log("wew")};
d.open("POST","/muse/data/post",!0);d.setRequestHeader("Content-type","application/json");d.send('{"client-data" : '+JSON.stringify(a)+',"script-name" : "favorite_communities_'+gllConnectionsData.userId+'"}')}r(c);t()}function t(){for(var a=document.querySelectorAll("#favourite_community_list a.remove_from_favourites"),c=0;c<a.length;c++)a[c].addEventListener("click",function(){if(document.querySelector('div.add_favorite_button.community_favorite[data-community="'+this.getAttribute("data-community_id")+
'"]'))document.querySelector('div[class="add_favorite_button community_favorite"][data-community="'+this.getAttribute("data-community_id")+'"]').click();else{var b=this,a=new XMLHttpRequest;a.onreadystatechange=function(){if(4==this.readyState&&200==this.status){var a=JSON.parse(this.responseText);initial_payload=0!=a.message&&Array.isArray(a.message)?a.message:[];null!=initial_payload?0==b.getAttribute("data-added")?initial_payload.push(b.getAttribute("data-community_id")):initial_payload.splice(initial_payload.indexOf(b.getAttribute("data-community_id")),
1):initial_payload=[b.getAttribute("data-community_id")];e(b,b.getAttribute("data-added")^1);a=new XMLHttpRequest;a.onreadystatechange=function(){4==this.readyState&&200==this.status&&console.log("wew")};a.open("POST","/muse/data/post",!0);a.setRequestHeader("Content-type","application/json");a.send('{"client-data" : '+JSON.stringify(initial_payload)+',"script-name" : "favorite_communities_'+gllConnectionsData.userId+'"}')}else return"failure"};a.open("GET","/muse/data/get/favorite_communities_"+
gllConnectionsData.userId,!0);a.send()}document.querySelector('div[data-community_id="'+this.getAttribute("data-community_id")+'"]').outerHTML="";0===document.querySelectorAll("#favourite_community_list div").length&&(document.getElementById("favourite_community_list").innerHTML='<div style="text-align:center;margin-top:50px;font-size:15px;">'+get_translation("NO_COMMUNITIES_ADDED")+"</div>")},!1)}function r(a){for(var c="",b=0;b<a.length;b++)c+='<div data-community_id="'+a[b].community_id+'"><div style="margin:5px;display:inline-block;"><img src="/communities/service/html/image?communityUuid='+
a[b].community_id+'" width="50" height="50"/></div><div style="font-size:15px;margin-left:15px;display:inline-block;"><a href="/communities/service/html/communityoverview?communityUuid='+a[b].community_id+'">'+a[b].community_name+'</a></div><div style="float: right;margin-right: 20px;line-height: 60px;font-size: 15px;"><a href="javascript:void(0);" class="remove_from_favourites" data-community_id="'+a[b].community_id+'">'+get_translation("ERASE")+"</a></div></div>";document.getElementById("favourite_community_list").innerHTML=
c}function p(a){var c=new XMLHttpRequest;c.onreadystatechange=function(){if(4==this.readyState&&200==this.status){var b=JSON.parse(this.responseText);if("function"==typeof a)a(b);else return b}else return"failure"};c.open("GET","/muse/data/get/favorite_communities_"+gllConnectionsData.userId,!0);c.send()}function n(a){for(var c=document.querySelectorAll(".lotusContent .lotusTable tbody tr"),b=0;b<c.length;b++){var d=c[b].querySelector("h4 a").getAttribute("href"),f=d.substring(d.indexOf("communityUuid=")+
14);d=document.createElement("DIV");d.classList.add("add_favorite_button");d.setAttribute("data-community",f);d.style.backgroundImage="url('/connections/resources/web/com.ibm.social.hikari.theme/sprite/lotusHSprite-8bit.png?etag=20180809.013226')";d.style.width="14px";d.style.height="15px";d.style.display="inline-block";d.style.marginLeft="8px";null!=a&&-1<a.indexOf(f)?e(d,!0):e(d,!1);f=document.createElement("span");d.addEventListener("click",function(){var a=this,b=new XMLHttpRequest;b.onreadystatechange=
function(){if(4==this.readyState&&200==this.status){var b=JSON.parse(this.responseText);initial_payload=0!=b.message&&Array.isArray(b.message)?b.message:[];null!=initial_payload?0==a.getAttribute("data-added")?initial_payload.push(a.getAttribute("data-community")):initial_payload.splice(initial_payload.indexOf(a.getAttribute("data-community")),1):initial_payload=[a.getAttribute("data-community")];e(a,a.getAttribute("data-added")^1);b=new XMLHttpRequest;b.onreadystatechange=function(){4==this.readyState&&
200==this.status&&console.log("wew")};b.open("POST","/muse/data/post",!0);b.setRequestHeader("Content-type","application/json");b.send('{"client-data" : '+JSON.stringify(initial_payload)+',"script-name" : "favorite_communities_'+gllConnectionsData.userId+'"}')}else return"failure"};b.open("GET","/muse/data/get/favorite_communities_"+gllConnectionsData.userId,!0);b.send()},!1);f.appendChild(d);c[b].querySelector("h4").appendChild(f)}}function e(a,c){c?(a.setAttribute("data-added","1"),a.setAttribute("title",
get_translation("FAVOURITED")),a.classList.remove("community_not_favorite"),a.classList.add("community_favorite")):(a.setAttribute("data-added","0"),a.setAttribute("title",get_translation("ADD_TO_FAVOURITES")),a.classList.remove("community_favorite"),a.classList.add("community_not_favorite"))}var h=new XMLHttpRequest;if(window.location.pathname.startsWith("/communities/")){k();var u=setInterval(function(){null!==document.getElementById("lconn_communities_catalog_widgets_ResultsDisplayWidget_0")&&
(m(),l(),clearInterval(u))},1E3)}window.location.pathname.startsWith("/communities/service/html/community/updates")||window.location.pathname.startsWith("/wikis/home")||window.location.pathname.startsWith("/communities/service/html/community/bookmarks")||window.location.pathname.startsWith("/blogs/")||window.location.pathname.startsWith("/metricssc/communitiesapp");if(window.location.pathname.startsWith("/communities/service/html/communitystart")||window.location.pathname.startsWith("/communities/service/html/communityoverview")||
window.location.pathname.startsWith("/communities/service/html/community/updates")||window.location.pathname.startsWith("/wikis/home")||window.location.pathname.startsWith("/communities/service/html/community/bookmarks")||window.location.pathname.startsWith("/blogs/")||window.location.pathname.startsWith("/metricssc/communitiesapp"))k(),p(function(a){var c=setInterval(function(){if(null!==document.getElementById("tabNavCommunityName")){var b=document.createElement("DIV");b.classList.add("add_favorite_button");
b.setAttribute("data-community",ic_comm_communityUuid);b.style.backgroundImage="url('/connections/resources/web/com.ibm.social.hikari.theme/sprite/lotusHSprite-8bit.png?etag=20180809.013226')";b.style.width="14px";b.style.height="15px";b.style.display="inline-block";b.style.marginLeft="8px";b.style.marginBottom="5px";null!=a.message&&-1<a.message.indexOf(ic_comm_communityUuid)?e(b,!0):e(b,!1);var d=document.createElement("span");b.addEventListener("click",function(){var b=this,a=new XMLHttpRequest;
a.onreadystatechange=function(){if(4==this.readyState&&200==this.status){var a=JSON.parse(this.responseText);initial_payload=0!=a.message&&Array.isArray(a.message)?a.message:[];null!=initial_payload?0==b.getAttribute("data-added")?initial_payload.push(b.getAttribute("data-community")):initial_payload.splice(initial_payload.indexOf(b.getAttribute("data-community")),1):initial_payload=[b.getAttribute("data-community")];e(b,b.getAttribute("data-added")^1);a=new XMLHttpRequest;a.onreadystatechange=function(){4==
this.readyState&&200==this.status&&console.log("wew")};a.open("POST","/muse/data/post",!0);a.setRequestHeader("Content-type","application/json");a.send('{"client-data" : '+JSON.stringify(initial_payload)+',"script-name" : "favorite_communities_'+gllConnectionsData.userId+'"}')}else return"failure"};a.open("GET","/muse/data/get/favorite_communities_"+gllConnectionsData.userId,!0);a.send()},!1);d.appendChild(b);document.getElementById("tabNavCommunityName").appendChild(d);clearInterval(c)}},500)})},
!0);